import { useState } from "react";
import type { FormEvent } from "react";
import { ArrowUpRight, Check, X } from "lucide-react";
import { toast } from "sonner";

type PackageName = "Starter Agent" | "Basic Agent" | "Premium Agent" | "Custom AI Agent";
const requirements = ["Customer Support", "Sales", "Lead Generation", "Competitor Research", "Market Research", "Marketing", "Booking/Appointments", "FAQ", "Product Recommendations", "Other"];
const packagePrices: Record<PackageName, string> = { "Starter Agent": "$400", "Basic Agent": "$799", "Premium Agent": "$1,500", "Custom AI Agent": "$3,000 – $25,000+" };

export default function OrderDialog({ packageName, close }: { packageName: PackageName; close: () => void }) {
  const [selected, setSelected] = useState<string[]>([]); const [sending, setSending] = useState(false); const [sent, setSent] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSending(true); const form = new FormData(event.currentTarget); const body = { customerName: String(form.get("name") || ""), companyName: String(form.get("company") || ""), customerEmail: String(form.get("email") || ""), customerPhone: String(form.get("phone") || ""), website: String(form.get("website") || ""), industry: String(form.get("industry") || ""), country: String(form.get("country") || ""), requirements: `What we do: ${form.get("business")}\nCustomers: ${form.get("customers")}\nProblems to solve: ${form.get("problems")}\nAgent should do: ${form.get("capabilities")}\nRequirements: ${selected.join(", ")}\nAdditional: ${form.get("additional")}`, suggestedPackage: packageName, suggestedPrice: packagePrices[packageName], packageReasoning: packageName === "Custom AI Agent" ? "Custom quotation request; do not auto-charge." : "Submitted from the package order form.", source: "order-form", status: "new" }; const response = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setSending(false); if (response.ok) setSent(true); else toast.error("We couldn't submit the order", { description: "Please try WhatsApp or email us directly." }); };
  return <div className="order-backdrop" role="dialog" aria-modal="true" aria-label={`${packageName} order form`}><div className="order-dialog"><button className="order-close" onClick={close} aria-label="Close"><X size={18} /></button>{sent ? <div className="order-success"><div className="order-success-icon"><Check size={22} /></div><span className="eyebrow eyebrow-dark"><span className="eyebrow-dot" /> Request received</span><h2>Your next step is in motion.</h2><p>AgentPlus has received your {packageName} request. We’ll review the requirements and contact you within 24 hours.</p><button className="button button-dark" onClick={close}>Back to AgentPlus <ArrowUpRight size={15} /></button></div> : <><div className="eyebrow eyebrow-dark"><span className="eyebrow-dot" /> Build your agent</div><h2>{packageName}</h2><div className="order-price">{packagePrices[packageName]} <span>{packageName === "Custom AI Agent" ? "estimated range · quotation" : "one-time build"}</span></div><form className="order-form" onSubmit={submit}><div className="order-grid"><input name="name" required placeholder="Your name" /><input name="company" required placeholder="Company name" /><input name="email" required type="email" placeholder="Work email" /><input name="phone" required placeholder="Phone / WhatsApp" /><input name="website" placeholder="Company website" /><input name="industry" required placeholder="Industry" /><input name="country" required placeholder="Country" /></div><textarea name="business" required placeholder="What does your company do?" /><textarea name="customers" required placeholder="Who are your customers?" /><textarea name="problems" required placeholder="What problems should the AI agent solve?" /><textarea name="capabilities" required placeholder="What should the agent be able to do?" /><div className="requirement-picker"><span>Agent requirements</span><div>{requirements.map((item) => <button type="button" className={selected.includes(item) ? "active" : ""} key={item} onClick={() => setSelected(selected.includes(item) ? selected.filter((value) => value !== item) : [...selected, item])}>{selected.includes(item) && <Check size={12} />}{item}</button>)}</div></div><textarea name="additional" placeholder="Tell us anything else you want your AI agent to do." /><button className="button button-dark" type="submit" disabled={sending}>{sending ? "Submitting request…" : packageName === "Custom AI Agent" ? "Submit custom project" : `Order ${packageName} · ${packagePrices[packageName]}`} <ArrowUpRight size={15} /></button><small>Submitting an order starts a consultation. Payment is requested only after requirements are confirmed.</small></form></>}</div></div>;
}
